crypto_pipeline:
  target: dev
  outputs:
    dev:
      type: postgres
      host: db
      port: 5432
      user: user
      password: password
      dbname: crypto_db
      schema: analytics
      threads: 4
