FROM apache/airflow:2.7.0-python3.11

USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends git \
    && rm -rf /var/lib/apt/lists/*

USER airflow

RUN pip install --no-cache-dir ccxt psycopg2-binary dbt-postgres clickhouse-connect
